Initialize fail_flag and fail_message even if single_core (#604)
* add new badge

* Initialize fail_flag and fail_message even if single_core

If running on a single chromosome, these variables were not being set, resulting in the
error:

Traceback (most recent call last):
  File "/opt/anaconda2/envs/HiCExplorer/bin/hicDetectLoops", line 7, in <module>
    main()
  File "/opt/anaconda2/envs/HiCExplorer/lib/python3.6/site-packages/hicexplorer/hicDetectLoops.py", line 1072, in main
    if fail_flag:
UnboundLocalError: local variable 'fail_flag' referenced before assignment

Co-authored-by: Björn Grüning <bjoern.gruening@gmail.com>